/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as NewRouteImport } from './routes/new'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as ReportsEditIdRouteImport } from './routes/reports.edit.$id'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminLabsRouteImport } from './routes/admin.labs'
import { Route as LabRouteImport } from './routes/lab'
import { Route as TeamRouteImport } from './routes/team'
import { Route as PatientsRouteImport } from './routes/patients'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsEditIdRoute = ReportsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => ReportsRoute,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLabsRoute = AdminLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/new': typeof NewRoute
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/edit/$id': typeof ReportsEditIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/setup': typeof AdminSetupRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/patients': typeof PatientsRoute
  '/lab': typeof LabRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/edit/$id': typeof ReportsEditIdRoute
  '/reports': typeof ReportsIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/setup': typeof AdminSetupRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/patients': typeof PatientsRoute
  '/lab': typeof LabRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/new': typeof NewRoute
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/edit/$id': typeof ReportsEditIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/setup': typeof AdminSetupRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/patients': typeof PatientsRoute
  '/lab': typeof LabRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/new'
    | '/reports'
    | '/settings'
    | '/reports/$id'
    | '/reports/edit/$id'
    | '/reports/'
    | '/login'
    | '/admin'
    | '/admin/setup'
    | '/admin/labs'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/settings'
    | '/patients'
    | '/lab'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalog' | '/new' | '/settings' | '/reports/$id' | '/reports/edit/$id' | '/reports' | '/login' | '/admin' | '/admin/setup' | '/admin/labs' | '/admin/reports' | '/admin/users' | '/admin/settings' | '/patients'
    | '/lab' | '/team'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/new'
    | '/reports'
    | '/settings'
    | '/reports/$id'
    | '/reports/edit/$id'
    | '/reports/'
    | '/login'
    | '/admin'
    | '/admin/setup'
    | '/admin/labs'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/settings'
    | '/patients'
    | '/lab'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  NewRoute: typeof NewRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  LoginRoute: typeof LoginRoute
  AdminRoute: typeof AdminRouteWithChildren
  LabRoute: typeof LabRouteImport
  TeamRoute: typeof TeamRouteImport
  PatientsRoute: typeof PatientsRouteImport
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/reports/edit/$id'
      preLoaderRoute: typeof ReportsEditIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/admin/labs'
      preLoaderRoute: typeof AdminLabsRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/users': {
      id: '/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminSetupRoute: typeof AdminSetupRoute
  AdminLabsRoute: typeof AdminLabsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSetupRoute: AdminSetupRoute,
  AdminLabsRoute: AdminLabsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ReportsRouteChildren {
  ReportsIdRoute: typeof ReportsIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  ReportsEditIdRoute: typeof ReportsEditIdRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIdRoute: ReportsIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  ReportsEditIdRoute: ReportsEditIdRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  NewRoute: NewRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  LoginRoute: LoginRoute,
  AdminRoute: AdminRouteWithChildren,
  LabRoute: LabRoute,
  TeamRoute: TeamRoute,
  PatientsRoute: PatientsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
